// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DDSBase.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_DDSBASE_H_
#define _FAST_DDS_GENERATED_DDSBASE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include "dataProcess.hpp"
#include "sqlite3/sqlite3.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DDSBASE_SOURCE)
#define DDSBASE_DllAPI __declspec( dllexport )
#else
#define DDSBASE_DllAPI __declspec( dllimport )
#endif // DDSBASE_SOURCE
#else
#define DDSBASE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DDSBASE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure DDSBase defined by the user in the IDL file.
 * @ingroup DDSBase
 */
class DDSBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DDSBase();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DDSBase();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DDSBase that will be copied.
     */
    eProsima_user_DllExport DDSBase(
            const DDSBase& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DDSBase that will be copied.
     */
    eProsima_user_DllExport DDSBase(
            DDSBase&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DDSBase that will be copied.
     */
    eProsima_user_DllExport DDSBase& operator =(
            const DDSBase& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DDSBase that will be copied.
     */
    eProsima_user_DllExport DDSBase& operator =(
            DDSBase&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x DDSBase object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DDSBase& x) const;

    /*!
     * @brief Comparison operator.
     * @param x DDSBase object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DDSBase& x) const;

    /*!
     * @brief This function copies the value in member str_json
     * @param _str_json New value to be copied in member str_json
     */
    eProsima_user_DllExport void str_json(
            const std::string& _str_json);

    /*!
     * @brief This function moves the value in member str_json
     * @param _str_json New value to be moved in member str_json
     */
    eProsima_user_DllExport void str_json(
            std::string&& _str_json);

    /*!
     * @brief This function returns a constant reference to member str_json
     * @return Constant reference to member str_json
     */
    eProsima_user_DllExport const std::string& str_json() const;

    /*!
     * @brief This function returns a reference to member str_json
     * @return Reference to member str_json
     */
    eProsima_user_DllExport std::string& str_json();

public:
  void setJson(Json::Value root);
  Json::Value getJson();

  void setStrJson(Json::Value root);
  std::string getStrJson();

public:
  sqlite3* getDB(std::string name);
  void setDB(std::string name);
  int sqliteExec(std::string nameDB,std::string cmd);
private:

  Json::Value m_root;
  std::string m_str_json;
  std::map<std::string,sqlite3*> m_DBMap;

};

#endif // _FAST_DDS_GENERATED_DDSBASE_H_



